name: magma build

on:
  push:
    branches:
      - 'master'

jobs:
  magma-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Magma Images
        run: ./build.sh
